import json
from groq import Groq  # type: ignore[import]

# ==========================================
# 1. SETUP YOUR API KEY HERE
# ==========================================
import os

# Replace 'YOUR_GROQ_API_KEY_HERE' with your actual Groq API key
client = Groq(api_key=os.environ.get("GROQ_API_KEY", "YOUR_GROQ_API_KEY_HERE"))

def generate_audit_report(json_path):
    print(f"Loading flagged anomalies from {json_path}...")
    
    # Load the JSON file generated by your pandas pipeline
    with open(json_path, 'r') as file:
        anomalies = json.load(file)
        
    if not anomalies:
        print("No anomalies to process. Ledger is clean!")
        return

    print(f"Found {len(anomalies)} anomalies. Sending to AI for analysis...\n")
    print("-" * 50)

    # ---------------------------------------------------------
    # STEP 2: THE PROMPT ENGINEERING
    # ---------------------------------------------------------
    # We create a specific "persona" for the AI so it sounds professional
    system_instruction = """
    You are a strict, highly analytical corporate auditor at KPMG.
    I will give you a JSON object representing a flagged financial transaction.
    Write a concise, 2-sentence explanation of why this transaction is suspicious 
    based on the 'flag_' fields that are marked true. Keep the tone professional.
    """

    audit_results = []

    # Loop through each anomaly and ask the AI to explain it
    for txn in anomalies:
        # Convert the single transaction dictionary into a string for the AI
        txn_string = json.dumps(txn, indent=2)
        
        print(f"Analyzing {txn['transaction_id']} (Vendor: {txn['vendor_name']})...")
        
        try:
            # Call the Groq API using Llama 3.1
            response = client.chat.completions.create(
                messages=[
                    {
                        "role": "system",
                        "content": system_instruction
                    },
                    {
                        "role": "user",
                        "content": f"Transaction Data:\n{txn_string}"
                    }
                ],
                model="llama-3.1-8b-instant",
            )
            explanation = response.choices[0].message.content.strip()
            
            # Save the result
            txn['ai_audit_note'] = explanation
            audit_results.append(txn)
            
            # Print to console so you can see it working
            print(f"AI NOTE: {explanation}\n")
            
        except Exception as e:
            print(f"Error analyzing {txn['transaction_id']}: {e}")

    # ---------------------------------------------------------
    # STEP 3: SAVE THE FINAL REPORT
    # ---------------------------------------------------------
    output_file = 'final_audit_report.json'
    with open(output_file, 'w') as out_file:
        json.dump(audit_results, out_file, indent=4)
        
    print("-" * 50)
    print(f"Success! Final human-readable report saved to {output_file}")

if __name__ == "__main__":
    # Make sure this matches the output of your pipeline!
    generate_audit_report("flagged_anomalies.json")